const customsMarkers = [
  // EXTRACTIONS
  { type: "extractions", icon: "E", name: "ZB10-11", info: "Main extraction, always open", lat: 527, lng: 56 },
  { type: "extractions", icon: "E", name: "Old Gas Station", info: "When green flares are present, extraction is available.", lat: 581, lng: 382 },
  { type: "extractions", icon: "E", name: "ZB10-13", info: "Activate Lever in Warehouse 4. Factory Exit Key to unlock ZB10-13 Gate (Factory)", lat: 645, lng: 644 },
  { type: "extractions", icon: "E", name: "Railroad Passage Extract", info: "Flare gun with Green cartridge", lat: 679, lng: 525 },
  { type: "extractions", icon: "E", name: "Trailer Park", info: "Main extraction, always open", lat: 629, lng: 1033 },
  { type: "extractions", icon: "E", name: "Crossroads", info: "Main extraction, always open", lat: 492, lng: 1044 },
  { type: "extractions", icon: "E", name: "Smuggler's Boat", info: "Campfire must be lit for extraction. Requires Note with code word Voron", lat: 260, lng: 736 },
  { type: "extractions", icon: "E", name: "Dorm V-EX", info: "The black SUV must be present for extraction. 5000 Rubles per player. Max 4 players.", lat: 172, lng: 518 },
  { type: "extractions", icon: "E", name: "Smuggler's Bunker", info: "Need (Note with Codeword Voron)", lat: 511, lng: 122 },

  // EXTRACTIONS CO-OP
  { type: "extractions_coop", icon: "EC", name: "Boiler Room Extract", info: "Requirements: Scav + PMC ", lat: 455, lng: 497 },

  // EXTRACTIONS SCAV
  { type: "extractions_scav", icon: "ES", name: "Factory Far Corner", info: "Always available", lat: 560, lng: 38 },
  { type: "extractions_scav", icon: "ES", name: "Old Gas Station Gate", info: "Always available", lat: 596, lng: 390 },
  { type: "extractions_scav", icon: "ES", name: "Warehouse 4", info: "Always available", lat: 419, lng: 356 },
  { type: "extractions_scav", icon: "ES", name: "Factory Shacks", info: "Always available", lat: 379, lng: 491 },
  { type: "extractions_scav", icon: "ES", name: "Warehouse 17", info: "Always available", lat: 464, lng: 653 },
  { type: "extractions_scav", icon: "ES", name: "Railroad To Tarkov", info: "Always available", lat: 615, lng: 873 },
  { type: "extractions_scav", icon: "ES", name: "Trailer Park Workers' Shake", info: "Always available", lat: 630, lng: 957 },
  { type: "extractions_scav", icon: "ES", name: "Railroad To Port", info: "Always available", lat: 343, lng: 850 },
  { type: "extractions_scav", icon: "ES", name: "Sniper RoadBlock", info: "Always available", lat: 263, lng: 691 },
  { type: "extractions_scav", icon: "ES", name: "Old Roadgate", info: "Always available", lat: 174, lng: 510 },
  { type: "extractions_scav", icon: "ES", name: "Railroad To Military Base", info: "Always available", lat: 165, lng: 201 },
  { type: "extractions_scav", icon: "ES", name: "Passage Between Rocks", info: "Always available", lat: 188, lng: 151 },
  { type: "extractions_scav", icon: "ES", name: "Military Base CP", info: "Always available", lat: 264, lng: 45 },
  { type: "extractions_scav", icon: "ES", name: "Scav Checkpoint", info: "Always available", lat: 418, lng: 37 },
  { type: "extractions_scav", icon: "ES", name: "Administration Gate", info: "Always available", lat: 444, lng: 20 },

  // BOSS
  { type: "boss", icon: "S", name: "Reshala", info: "Boss —  patrols sawmill area", lat: 240, lng: 495 },
  { type: "boss", icon: "S", name: "Reshala", info: "Boss —  patrols sawmill area", lat: 363, lng: 293 },
  { type: "boss", icon: "S", name: "Reshala", info: "Boss —  patrols sawmill area", lat: 534, lng: 493 },

  // Goons
  { type: "goons", icon: "G", name: "The Goons", info: "Spawn aléatoire - zone nord", lat: 511, lng: 501 },
  { type: "goons", icon: "G", name: "The Goons", info: "Spawn aléatoire - zone nord", lat: 515, lng: 630 },

  // PMC spawn
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 225, lng: 325 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 183, lng: 284 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 217, lng: 167 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 252, lng: 103 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 344, lng: 147 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 351, lng: 32 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 495, lng: 72 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 509, lng: 117 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 460, lng: 191 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 504, lng: 213 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 480, lng: 222 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 626, lng: 1037 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 478, lng: 1028 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 400, lng: 924 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 283, lng: 709 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 532, lng: 191 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 491, lng: 316 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 461, lng: 378 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 597, lng: 406 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 522, lng: 638 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 521, lng: 698 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 616, lng: 841 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 527, lng: 858 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 513, lng: 891 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 528, lng: 914 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 617, lng: 921 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 480, lng: 946 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 439, lng: 868 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 355, lng: 838 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 535, lng: 977 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 515, lng: 322 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 447, lng: 120 },

  // Quests
  { type: "quests", icon: "Q", name: "BP Depot", info: "Fuel Tank #1", lat: 375, lng: 264 , questId: "59c124d686f774189b3c843f"},
  { type: "quests", icon: "Q", name: "BP Depot", info: "Fuel Tank #2", lat: 407, lng: 601 , questId: "59c124d686f774189b3c843f"},
  { type: "quests", icon: "Q", name: "BP Depot", info: "Fuel Tank #3", lat: 585, lng: 361 , questId: "59c124d686f774189b3c843f"},
  { type: "quests", icon: "Q", name: "BP Depot", info: "Fuel Tank #4", lat: 558, lng: 1046 , questId: "59c124d686f774189b3c843f"},
  { type: "quests", icon: "Q", name: "Work Smarter", info: "Optional to get the hint but you have to find it randomly somewhere on the map 100% spawn but not necessary. Green Smoke and searchlight has to be on to use the extract", lat: 511, lng: 222 , questId: "675c1cf4a757ddd00404f0a3"},
  { type: "quests", icon: "Q", name: "Background Check", info: "Inside the truck. Requires the Machinery Key to unlock the truck door", lat: 399, lng: 598 , questId: "5936da9e86f7742d65037edf"},
  { type: "quests", icon: "Q", name: "Rite Of Passage", info: "Eliminate 10 Scavs at the old gas station on Customs", lat: 570, lng: 366 , questId: "675c1ec7a46173572a0bf20a"},
  { type: "quests", icon: "Q", name: "Rite Of Passage", info: "Eliminate 10 Scavs at the new gas station on Customs", lat: 353, lng: 293 , questId: "675c1ec7a46173572a0bf20a"},
  { type: "quests", icon: "Q", name: "Belka and Strelka", info: "Survive and extract from Customs through Railroad Passage", lat: 672, lng: 519 , questId: "675c3507a06634b5110e3c18"},
  { type: "quests", icon: "Q", name: "Operation Aquarius - Part 1", info: "(Dorm Room 206 key required)", lat: 80, lng: 316 , questId: "59689fbd86f7740d137ebfc4"},
  { type: "quests", icon: "Q", name: "The Extortionist", info: "You'll find the Unknown Key on the body in the bushes. / 443 327. Inside the Unknown Cabin - requires the Unknown Key to unlock.", lat: 507, lng: 675 , questId: "596b43fb86f77457ca186186"},
  { type: "quests", icon: "Q", name: "Golden Swag", info: "Find the Golden Zibbo lighter (303 key required)", lat: 94, lng: 485 , questId: "5979eee086f774311955e614"},
  { type: "quests", icon: "Q", name: "Golden Swag", info: "Stash the Golden Zibbo lighter in the bunkhouse in the trailer parking lot on Customs (Requires the Trailer Park Cabin Key.)", lat: 603, lng: 901 , questId: "5979eee086f774311955e614"},
  { type: "quests", icon: "Q", name: "Pharmacist", info: "Dorm Room 114 Key is in a jacket in the trunk of the blue car.", lat: 395, lng: 111 , questId: "5969f9e986f7741dde183a50"},
  { type: "quests", icon: "Q", name: "Pharmacist", info: "Location: Dorm Room 114 - on top of the safe.", lat: 34, lng: 372 , questId: "5969f9e986f7741dde183a50"},
  { type: "quests", icon: "Q", name: "Chemical - Part 1", info: "Find Secure Case For Documents 0013. Location is randomized, inside the train car", lat: 534, lng: 201 , questId: "5979f9ba86f7740f6c3fe9f2"},
  { type: "quests", icon: "Q", name: "Chemical - Part 2", info: "Find Sealed letter with a TG logo and Sliderkey Secure Flash Drive. (Dorm room 220 key required)", lat: 42, lng: 547 , questId: "5979f9ba86f7740f6c3fe9f2"},
  { type: "quests", icon: "Q", name: "Tigr Safari", info: "Mark the vehicle with an MS2000 Marker #1", lat: 392, lng: 686 , questId: "5a27b7a786f774579c3eb376"},
  { type: "quests", icon: "Q", name: "Tigr Safari", info: "Mark the vehicle with an MS2000 Marker #2", lat: 403, lng: 187 , questId: "5a27b7a786f774579c3eb376"},
  { type: "quests", icon: "Q", name: "Tigr Safari", info: "Mark the vehicle with an MS2000 Marker #3", lat: 417, lng: 119 , questId: "5a27b7a786f774579c3eb376"},
  { type: "quests", icon: "Q", name: "Chemical - Part 4", info: "Locate the transport with the chemicals on Customs and mark the vehicle with an MS2000 Marker", lat: 469, lng: 213 , questId: "597a0f5686f774273b74f676"},
  { type: "quests", icon: "Q", name: "Out of Curiosity", info: "Locate the transport with the chemicals on Customs and mark the vehicle with an MS2000 Marker", lat: 466, lng: 213 , questId: "597a160786f77477531d39d2"},
  { type: "quests", icon: "Q", name: "Big Customer", info: "Locate the transport with the chemicals on Customs and mark the vehicle with an MS2000 Marker", lat: 473, lng: 212 , questId: "597a171586f77405ba6887d3"},
  { type: "quests", icon: "Q", name: "Passion for Ergonomics", info: "Locate and obtain the customized tool set at the garage complex on Customs", lat: 573, lng: 1027 , questId: "675c1570526ff496850895d9"},
  { type: "quests", icon: "Q", name: "Farming - Part 3", info: "Inside the Customs Office behind the printer next to the metal shelves (or next to the desk)(Tarcone Director's office key required)", lat: 494, lng: 911 , questId: "5ac3462b86f7741d6118b983"},
  { type: "quests", icon: "Q", name: "Shaking Up the Teller", info: "Under the bed in Dorm Room 203 (Dorm room 203 key required)", lat: 93, lng: 566 , questId: "5967725e86f774601a446662"},
  { type: "quests", icon: "Q", name: "Abandoned Cargo", info: "Locate and mark the first special TerraGroup cargo with an MS2000 Marker on Customs", lat: 530, lng: 896 , questId: "675c03d1f7da9792a405549a"},
  { type: "quests", icon: "Q", name: "Abandoned Cargo", info: "Locate and mark the second special TerraGroup cargo with an MS2000 Marker on Customs", lat: 443, lng: 587 , questId: "675c03d1f7da9792a405549a"},
  { type: "quests", icon: "Q", name: "Abandoned Cargo", info: "Locate and mark the third special TerraGroup cargo with an MS2000 Marker on Customs", lat: 458, lng: 637 , questId: "675c03d1f7da9792a405549a"},
  { type: "quests", icon: "Q", name: "Abandoned Cargo", info: "Locate and mark the fourth special TerraGroup cargo with an MS2000 Marker on Customs", lat: 460, lng: 601 , questId: "675c03d1f7da9792a405549a"},
  { type: "quests", icon: "Q", name: "Abandoned Cargo", info: "Locate and mark the fifth special TerraGroup cargo with an MS2000 Marker on Customs", lat: 466, lng: 554 , questId: "675c03d1f7da9792a405549a"},
  { type: "quests", icon: "Q", name: "Abandoned Cargo", info: "Locate and mark the sixth special TerraGroup cargo with an MS2000 Marker on Customs", lat: 451, lng: 640 , questId: "675c03d1f7da9792a405549a"},
  { type: "quests", icon: "Q", name: "Abandoned Cargo", info: "Locate and mark the seventh special TerraGroup cargo with an MS2000 Marker on Customs", lat: 436, lng: 642 , questId: "675c03d1f7da9792a405549a"},
  { type: "quests", icon: "Q", name: "Shipment Tracking", info: "Locate and obtain the TerraGroup shipment lists on Customs. Hand over the found information", lat: 856, lng: 608 , questId: "675c047fa46173572a0bd878"},
  { type: "quests", icon: "Q", name: "Closer to the People", info: "Locate and obtain the delivery crew's shipment notes on Customs. Hand over the found information", lat: 444, lng: 611 , questId: "675c04f4db8807b75d0f38e8"},
  { type: "quests", icon: "Q", name: "Break the Deal", info: "Stash a DVL-10 sniper rifle, Stash a DVL-10 magazine, Stash an ELCAN SpecterDR scope, Stash a pack of any 7.62x51 ammo at the specified spot on customs.", lat: 410, lng: 446 , questId: "675c085d59b0575973005f52"},
  { type: "quests", icon: "Q", name: "Private Club", info: "Locate and obtain Skier's wallet on Customs", lat: 781, lng: 655 , questId: "675c3582f6ddc329a90f9c6d"},
];
