const woodsMarkers = [
  // EXTRACTIONS
  { type: "extractions", icon: "E", name: "Outskirts",     info: "Main west extraction", lat: 75, lng: 174},
  { type: "extractions", icon: "E", name: "UN Roadblock",  info: "North extraction",     lat: 121,  lng: 742 },
  { type: "extractions", icon: "E", name: "ZB-014",        info: "Requires key ZB-014",  lat: 265, lng: 110 },
  { type: "extractions", icon: "E", name: "RUAF Gate",     info: "South extraction",     lat: 38, lng: 484 },
  { type: "extractions", icon: "E", name: "ZB-016",        info: "When green flares are present, extraction is available", lat: 293, lng: 647 },
  { type: "extractions", icon: "E", name: "Northern UN Roadblock",        info: "Always Open",  lat: 351, lng: 752 },
  { type: "extractions", icon: "E", name: "Vridge V EX",       info: "The black SUV must be present for extraction / 5,000 Roubles each (influenced by Scav Karma)", lat: 631, lng: 708 },
  { type: "extractions", icon: "E", name: "Power Line Passage",       info: "Requirements: Green Flare Extract - Make sure to be in the Flare firing area. After firing the flare keep running until the timer appears - it  will take a bit of running before you see it", lat: 343, lng: 83 },

  // EXTRACTION SCAV
  { type: "extractions_scav", icon: "ES", name: "Scav Extraction", info: "Scav House", lat: 151, lng: 130 },
  { type: "extractions_scav", icon: "ES", name: "Scav Extraction", info: "Dead man's Place", lat: 143, lng: 281 },
  { type: "extractions_scav", icon: "ES", name: "Scav Extraction", info: "The Boat", lat: 166, lng: 284 },
  { type: "extractions_scav", icon: "ES", name: "Scav Extraction", info: "Scav Bunker", lat: 758, lng: 248 },
  { type: "extractions_scav", icon: "ES", name: "Scav Extraction", info: "Scav Bridge", lat: 848, lng: 333 },
  { type: "extractions_scav", icon: "ES", name: "Scav Extraction", info: "Mountain Stash", lat: 441, lng: 528 },
  { type: "extractions_scav", icon: "ES", name: "Scav Extraction", info: "Eastern Stash", lat: 329, lng: 729 },
  { type: "extractions_scav", icon: "ES", name: "Scav Extraction", info: "Old Railway Depot", lat: 212, lng: 736 },

  // EXTRACTIONS CO-OP
  { type: "extractions_coop", icon: "EC", name: "Factory Gate", info: "Requirements: Scav + PMC ", lat: 71, lng: 629 },
  { type: "extractions_coop", icon: "EC", name: "Friendship Bridge", info: "Requirements: Scav + PMC ", lat: 842, lng: 327 },

  // BOSS
  { type: "boss", icon: "S", name: "Shturman", info: "Boss —  patrols sawmill area", lat: 335, lng: 370 },
  { type: "boss", icon: "S", name: "Shturman", info: "Boss — patrols sawmill area", lat: 249, lng: 313 },
  { type: "boss", icon: "S", name: "Shturman", info: "Boss — patrols sawmill area", lat: 393, lng: 351 },

  // Goons
  { type: "goons", icon: "G", name: "The Goons", info: "Spawn aléatoire - zone nord", lat: 634, lng: 217 },
  { type: "goons", icon: "G", name: "The Goons", info: "Spawn aléatoire - zone nord", lat: 762, lng: 253 },
  { type: "goons", icon: "G", name: "The Goons", info: "Spawn aléatoire - zone nord", lat: 780, lng: 310 },
  { type: "goons", icon: "G", name: "The Goons", info: "Spawn aléatoire - zone nord", lat: 759, lng: 446 },

  // PMC spawn
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 758, lng: 157 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 683, lng: 166 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 590, lng: 137 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 509, lng: 248 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 354, lng: 145 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 290, lng: 122 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 179, lng: 110 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 135, lng: 59 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 128, lng: 115 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 93, lng: 76 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 93, lng: 157 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 108, lng: 229 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 187, lng: 249 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 726, lng: 357 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 668, lng: 347 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 411, lng: 299 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 668, lng: 437 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 718, lng: 566 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 569, lng: 574 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 640, lng: 671 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 517, lng: 793 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 436, lng: 560 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 391, lng: 612 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 401, lng: 727 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 338, lng: 707 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 309, lng: 730 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 292, lng: 733 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 165, lng: 737 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 152, lng: 627 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 256, lng: 732 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 112, lng: 745 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 84, lng: 584 },
  { type: "spawn", icon: "SP", name: "PMC Spawn", info: "PMC spawn point", lat: 65, lng: 456 },

  // TRANSIT
  { type: "transit", icon: "T", name: "Transit", info: "Transit To Lighthouse", lat: 79, lng: 79 },
  { type: "transit", icon: "T", name: "Transit", info: "Transit To Reserve", lat: 73, lng: 239 },
  { type: "transit", icon: "T", name: "Transit", info: "Transit To Customs", lat: 39, lng: 489 },
  { type: "transit", icon: "T", name: "Transit", info: "Transit To Factory", lat: 77, lng: 628 },

  // Quests
  { type: "quests", icon: "Q", name: "Introduction", info: "Jeager's Message - Underneath the wooden lookout post.", lat: 299, lng: 560 , questId: "5d2495a886f77425cd51e403"},
  { type: "quests", icon: "Q", name: "Thrifty Stash - ZB-014", info: "Stash an Iskra lunch box & 0.6L water bottle in the broken crate beside the wooden crate in the ZB-014 bunker", lat: 261, lng: 114 , questId: "5d25b6be86f77444001e1b89"},
  { type: "quests", icon: "Q", name: "Thrifty Stash - ZB-016", info: "Stash an Iskra lunch box & 0.6L water bottle in the broken crate beside the wooden crate in the ZB-016 bunker", lat: 291, lng: 651 , questId: "5d25b6be86f77444001e1b89"},
  { type: "quests", icon: "Q", name: "Steady Signal - Weather Station 1", info: "Mark First Weather Station", lat: 715, lng: 143 , questId: "6578ec473dbd035d04531a8d"},
  { type: "quests", icon: "Q", name: "Steady Signal - Weather Station 2", info: "Mark Second Weather Station", lat: 488, lng: 528 , questId: "6578ec473dbd035d04531a8d"},
  { type: "quests", icon: "Q", name: "Steady Signal - Weather Station 3", info: "Mark Third Weather Station", lat: 658, lng: 458 , questId: "6578ec473dbd035d04531a8d"},
  { type: "quests", icon: "Q", name: "Steady Signal - Weather Station 4", info: "Mark Fourth Weather Station", lat: 96, lng: 238 , questId: "6578ec473dbd035d04531a8d"},
  { type: "quests", icon: "Q", name: "Steady Signal - Weather Station 5", info: "Mark Fifth Weather Station", lat: 142, lng: 699 , questId: "6578ec473dbd035d04531a8d"},
  { type: "quests", icon: "Q", name: "Supply Plan", info: "Underneath bed in cabin #3", lat: 357, lng: 400 , questId: "596a0e1686f7741ddf17dbee"},
  { type: "quests", icon: "Q", name: "Search Mission", info: "USEC Temporary Camp", lat: 600, lng: 210 , questId: "5fd9fad9c1ce6b1a3b486d00"},
  { type: "quests", icon: "Q", name: "Search Mission", info: "Prapor's Convoy", lat: 692, lng: 270 , questId: "5fd9fad9c1ce6b1a3b486d00"},
  { type: "quests", icon: "Q", name: "Gratitude", info: "Beside the barrels on the wooden jetty", lat: 241, lng: 382 , questId: "5ae449b386f77446d8741719"},
  { type: "quests", icon: "Q", name: "A Helping Hand", info: "Location: It can be found in 1 of 2 locations in the northwest building of the train depot. The depot can only be accessed via the BTR Driver's taxi service    First spawn under the table next to the bed. Second spawn on the desk in the back office", lat: 221, lng: 791 , questId: "6752f6d83038f7df520c83e8"},
  { type: "quests", icon: "Q", name: "Health Care Privacity - Part 3", info: "Look for the blood on the right sliding door of the crashed car.", lat: 163, lng: 457 , questId: "5a68665c86f774255929b4c7"},
  { type: "quests", icon: "Q", name: "Hunting Trip", info: "Eliminate Shturman with a headshot from over 75 meters away while using an M700 Sniper rifle with the Burris FullField TAC30 1-4x24 30mm riflescope.", lat: 329, lng: 373 , questId: "5d25e4ca86f77409dd5cdf2c"},
  { type: "quests", icon: "Q", name: "The Blood Of War - Part 3", info: "Requirements: MS2000 Marker. Oil Barrels #1", lat: 363, lng: 168 , questId: "5c10f94386f774227172c572"},
  { type: "quests", icon: "Q", name: "The Blood Of War - Part 3", info: "Requirements: MS2000 Marker. Oil Barrels #2", lat: 291, lng: 606 , questId: "5c10f94386f774227172c572"},
  { type: "quests", icon: "Q", name: "The Blood Of War - Part 3", info: "Requirements: MS2000 Marker. Oil Barrels #3", lat: 440, lng: 533 , questId: "5c10f94386f774227172c572"},
  { type: "quests", icon: "Q", name: "The Huntsman Path - Woods Keeper", info: "Locate, Kill Shturman and extract with the key", lat: 321, lng: 362 , questId: "5d25e2ee86f77443e35162ea"},
];
